/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Sala;

import Controllers.SalaController;
import Models.BusinessObject.BOCategoria;
import Models.BusinessObject.BOSala;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class _Categoria extends javax.swing.JPanel {
    Sala sala;
    BOCategoria categoria;
      
    private static final ArrayList<String> urls = new ArrayList<String>(){{
        add("1.jpg");
        add("2.png");
        add("3.png");
    }};
    /**
     * Creates new form _Categoria
     */
    public _Categoria() {
        initComponents();
    }
        
    public _Categoria(Sala sala,BOCategoria cat) {
        initComponents();
        this.sala = sala;
        this.categoria = cat;
        String url = urls.get(cat.getIdCategoria() - 1);
        btnImagen.setIcon(new ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\Adivinando\\src\\Recursos\\" + url));
        lblNombre.setText(cat.getDescripcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        btnImagen = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setFont(new java.awt.Font("Buxton Sketch", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");

        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votarPorCategoria(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void votarPorCategoria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votarPorCategoria
        // TODO add your handling code here:
        sala.votarPorCategoria(this.categoria);
    }//GEN-LAST:event_votarPorCategoria


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImagen;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

    void btnDisable() {
        btnImagen.setEnabled(false);
        btnImagen.setBackground(new Color(180,180,180));
    }
}
