/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Sala;

/**
 *
 * @author User
 */
public class _JugadorItemSecundario extends javax.swing.JPanel {

    /**
     * Creates new form _JugadorItemSecundario
     */
    public _JugadorItemSecundario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserIcon = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblCheck = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 232, 200));

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/user.png"))); // NOI18N

        lblUser.setFont(new java.awt.Font("Buxton Sketch", 0, 30)); // NOI18N
        lblUser.setText("Jugador");

        lblCheck.setBackground(new java.awt.Color(192, 232, 200));
        lblCheck.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCheck.setText("Listo!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setLblUserText(String text) {
        this.lblUser.setText(text);
    }
    
    public void deleteChk(){
        lblCheck.setVisible(false);
    } 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserIcon;
    // End of variables declaration//GEN-END:variables
}
