/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Sala;

import Controllers.SalaController;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class _JugadorItem extends javax.swing.JPanel {
    Sala mainView;
    /**
     * Creates new form _JugadorItem
     */
    public _JugadorItem() {
        initComponents();
    }
    public _JugadorItem(Sala mainView) {
        initComponents();
        this.mainView = mainView;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserIcon = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        chkListo = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/user.png"))); // NOI18N

        lblUser.setFont(new java.awt.Font("Buxton Sketch", 0, 36)); // NOI18N
        lblUser.setText("Jugador");

        chkListo.setBackground(new java.awt.Color(192, 232, 200));
        chkListo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkListo.setSelected(true);
        chkListo.setText("Listo!");
        chkListo.setEnabled(false);
        chkListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chkListo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(chkListo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkListoActionPerformed
        // TODO add your handling code here:
        if(chkListo.isSelected()){
            chkListo.setBackground(new Color(192,232,200));
            this.setBackground(new Color(192,232,200));
        }
        else{
            chkListo.setBackground(Color.WHITE);
            this.setBackground(Color.WHITE);
        }
        this.mainView.setListo(chkListo.isSelected());
    }//GEN-LAST:event_chkListoActionPerformed

    public void setLblUserText(String text) {
        this.lblUser.setText(text);
    }
    
    public void setBG(Color color){
        this.setBackground(color);
    }
    
    public void setAsPlayer(){
        chkListo.setEnabled(true);
        chkListo.setSelected(false);
        chkListo.setBackground(Color.WHITE);
    }
    
    public void deleteChk(){
        chkListo.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton chkListo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserIcon;
    // End of variables declaration//GEN-END:variables
}
